### ISSUE TITLE
Error when handling SocketIOException

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.abode#27]
While exercising the tests for HomeAssistant, I see this unexpected failure:

```
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
      self.run()
    File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
      self._target(*self._args, **self._kwargs)
    File "/Users/jaraco/code/home-assistant/core/.venv/lib/python3.12/site-packages/jaraco/abode/socketio.py", line 166, in _run
      self._step(intervals)
    File "/Users/jaraco/code/home-assistant/core/.venv/lib/python3.12/site-packages/jaraco/abode/socketio.py", line 205, in _step
      handler(event)
    File "/Users/jaraco/code/home-assistant/core/.venv/lib/python3.12/site-packages/jaraco/abode/socketio.py", line 252, in _on_websocket_text
      handler(message)
    File "/Users/jaraco/code/home-assistant/core/.venv/lib/python3.12/site-packages/jaraco/abode/socketio.py", line 287, in _on_engineio_message
      handler(data)
    File "/Users/jaraco/code/home-assistant/core/.venv/lib/python3.12/site-packages/jaraco/abode/socketio.py", line 302, in _on_socketio_error
      raise SocketIOException(ERRORS.SOCKETIO_ERROR, details=_message_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: Exception.__init__() got an unexpected keyword argument 'details'
```

**Comment by jaraco** [comment]
Support for `details` was dropped in 517a7b1563de8e5c65094421c5c61e3a21248881, part of the 4.0.0 release.
